import { IEntireAudiobookAPIData } from '../../src/models/audiobook';

export const AudiobookData: IEntireAudiobookAPIData[] = [
  {
    id: '0',
    name: 'Rich Dad Poor Dad',
    desc: 'What the Rich Teach Their Kids About Money - That the Poor and Middle Class Do Not!',
    img: 'https://m.media-amazon.com/images/I/51AHZGhzZEL._SL500_.jpg',
    writtenBy: 'Robert T. Kiyosaki',
    narratedBy: 'Tim Wheeler',
    lang: 'English',
    ratings: 4.7,
    len: '6 hrs and 9 mins',
    releaseDate: '15-06-12',
    publisher: 'Brilliance Audio',
    category: 'Personal finance',
    fileUrl:
      'https://tribeofnoisestorage.blob.core.windows.net/music/c9c84bcc00f348f658d608fdae8ba903.mp3',
  },
  {
    id: '1',
    name: 'Atomic Habits',
    desc: 'An Easy and Proven Way to Build Good Habits and Break Bad Ones',
    img: 'https://m.media-amazon.com/images/I/41wuB-s8vRL._SL500_.jpg',
    writtenBy: 'James Clear',
    narratedBy: 'James Clear',
    lang: 'English',
    ratings: 4.8,
    len: '5 hrs and 35 mins',
    releaseDate: '18-10-18',
    publisher: 'Penguin Audio',
    category: 'Psychology',
    fileUrl:
      'https://tribeofnoisestorage.blob.core.windows.net/music/13bbe764d8c38dd77a1eb738058e5a3c.mp3',
  },
  {
    id: '2',
    name: 'The Subtle Art of Not Giving a F*ck',
    desc: 'A Counterintuitive Approach to Living a Good Life',
    img: 'https://m.media-amazon.com/images/I/51MT0MbpD7L._SL500_.jpg',
    writtenBy: 'Mark Manson',
    narratedBy: 'Roger Wayne',
    lang: 'English',
    ratings: 4.5,
    len: '5 hrs and 17 mins',
    releaseDate: '13-09-16',
    publisher: 'HarperAudio',
    category: 'Self Help',
    fileUrl:
      'https://tribeofnoisestorage.blob.core.windows.net/music/fcc168bdb12727023a7a8e67298d0ff2.mp3',
  },
  {
    id: '3',
    name: 'The Alchemist',
    desc: 'A Fable About Following Your Dream',
    img: 'https://m.media-amazon.com/images/I/517pfctTa9L._SL500_.jpg',
    writtenBy: 'Paulo Coelho',
    narratedBy: 'eremy Irons',
    lang: 'English',
    ratings: 4.7,
    len: '4 hrs',
    releaseDate: '26-12-04',
    publisher: 'HarperAudio',
    category: 'Genre Fiction',
    fileUrl:
      'https://tribeofnoisestorage.blob.core.windows.net/music/6c9048255985c999b1233ed71edba617.mp3',
  },
  {
    id: '4',
    name: 'Make Time',
    desc: 'How to focus on what matters every day',
    img: 'https://m.media-amazon.com/images/I/51gQ7pHF-zL._SL500_.jpg',
    writtenBy: 'Jake Knapp, John Zeratsky',
    narratedBy: 'Jake Knapp, John Zeratsky',
    lang: 'English',
    ratings: 4.5,
    len: '4 hrs and 58 mins',
    releaseDate: '27-09-18',
    publisher: 'Penguin Books Ltd',
    category: 'Personal Success',
    fileUrl:
      'https://tribeofnoisestorage.blob.core.windows.net/music/8b9111de37b62c141fd1cdf2286c50be.mp3',
  },
  {
    id: '5',
    name: 'Never Split the Difference',
    desc: 'Negotiating as if Your Life Depended on It',
    img: 'https://m.media-amazon.com/images/I/51TSWCruAHL._SL500_.jpg',
    writtenBy: 'Chris Voss, Tahl Raz',
    narratedBy: 'Michael Kramer',
    lang: 'English',
    ratings: 4.7,
    len: '8 hrs and 7 mins',
    releaseDate: '20-06-19',
    publisher: 'Penguin Audio',
    category: 'Management',
    fileUrl:
      'https://tribeofnoisestorage.blob.core.windows.net/music/f6dc2538a1a480b0fe1cf954c119e1f4.mp3',
  },
  {
    id: '6',
    name: 'Ikigai',
    desc: 'The Japanese Secret to a Long and Happy Life',
    img: 'https://m.media-amazon.com/images/I/511HccWipML._SL500_.jpg',
    writtenBy: 'Héctor García, Francesc Miralles',
    narratedBy: 'Naoko Mori',
    lang: 'English',
    ratings: 4.5,
    len: '3 hrs and 23 mins',
    releaseDate: '18-09-17',
    publisher: 'Random House Audiobooks',
    category: 'Spirituality',
    fileUrl:
      'https://tribeofnoisestorage.blob.core.windows.net/music/5148dcf6c53777ba4aa2119c4cf0f0e1.mp3',
  },
];
