import { Button, Container } from '@mui/material';
import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container maxWidth="xl">
        <h1>Home Page</h1>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Fuga
          consequatur magni harum dolorem voluptas ad dicta deleniti sint, modi
          fugiat, temporibus, molestiae omnis consequuntur ratione cum ipsam
          consectetur enim cupiditate? Cum sint expedita porro voluptatem
          repellat impedit dicta odit rem quaerat sapiente, dolor omnis eaque
          recusandae error beatae odio incidunt eius fuga voluptates. Possimus
          quibusdam deserunt beatae rerum inventore ratione! Perferendis
          blanditiis incidunt aut facere nostrum ullam maxime sunt harum
          reprehenderit obcaecati labore eveniet saepe rerum, nesciunt, ab quod
          pariatur quidem fugit qui quaerat, excepturi dignissimos. Iure, at
          nesciunt. Et! Soluta quas magni possimus veniam illo necessitatibus
          blanditiis nam labore mollitia porro similique, molestias, optio
          neque! Distinctio aut excepturi dolores explicabo nemo itaque,
          voluptatum vero quas! Officia voluptatem qui nisi? Velit vero eveniet
          ipsam temporibus officiis voluptate, quibusdam ipsa debitis doloribus
          deserunt nam esse recusandae fugit quisquam, perspiciatis aut sunt
          natus facilis sequi deleniti! Suscipit expedita inventore a deserunt
          magni? Quam, aliquam quod qui impedit eum vel deserunt a quasi quia
          alias optio dolorem possimus expedita in voluptatibus sint, ipsam
          officia maxime voluptate eaque, rem quae voluptatem fugiat
          consectetur! Alias. Veniam quibusdam maiores minima cum neque dolore
          inventore quod voluptatibus sequi quas debitis non illo saepe ducimus
          labore culpa, dolores eum rem laudantium qui dolor odio facere
          voluptates. Magnam, numquam. Praesentium consectetur a cupiditate?
          Aliquam commodi fugiat nesciunt. Ad pariatur sed repudiandae,
          exercitationem id labore voluptatem nulla non sit. Iste maxime fuga
          perferendis. Consequatur, velit maiores quia amet soluta fugiat! Eum
          distinctio dolorem ipsa nulla impedit suscipit eveniet corrupti
          mollitia fugiat, voluptates eius vero consectetur, in doloremque quis
          accusamus cumque quam sed iusto blanditiis fuga tenetur? Iusto vel
          animi accusantium! Cupiditate, distinctio harum? Ab, ad. Maiores
          reiciendis eveniet explicabo sed inventore facere nam perferendis
          iusto libero in mollitia aut consequatur distinctio consequuntur
          soluta sequi delectus, ad debitis illo blanditiis eligendi? Totam
          voluptas maiores quod earum esse ut, molestiae est laborum, dolore
          illo quisquam incidunt, illum debitis voluptates ab consequatur
          voluptate. Perspiciatis modi corrupti minima, soluta quidem ea!
          Architecto, odio saepe. Vero nihil natus quae eligendi facere sunt
          consequuntur, quisquam et inventore expedita quam officiis harum,
          officia a voluptatum. Minima nisi quisquam maxime voluptatum unde
          delectus sint? Quidem suscipit impedit minus. Earum libero, est, esse
          quibusdam molestias rem corporis debitis, sunt similique excepturi
          quam amet obcaecati vitae eos nulla quo? Magni, corporis quam.
          Laudantium repudiandae nostrum deleniti accusamus, rerum soluta
          dolores. Dicta facilis soluta cumque fugit. Perferendis voluptate
          nesciunt a harum, temporibus cumque ratione eligendi rem, autem optio
          explicabo. Possimus, eaque consequatur earum quasi magnam soluta porro
          velit ea vero aut? Ad neque sit, ullam sint id magni enim reiciendis
          delectus nam aperiam tempore ipsum culpa cupiditate ratione rem
          aliquam et placeat perferendis. Delectus architecto doloremque vitae
          et unde cupiditate enim?
        </p>
      </Container>
    </>
  );
};

export default Home;
